Repository J-algorithm/J-algorithm, pull requests merged in 2024-02, with the labels that each got.

#14 [4주차] 과제 제출합니다.
  완전탐색/모음 사전/PGS_모음사전_공진호.java
  완전탐색/전력망을 둘로 나누기 /PGS_전력망을둘로나누기_공진호.java
  완전탐색/피로도/PGS_피로도_공진호.java
Labels: ✨ Submit

#12 [4주차] 과제 제출합니다.
  완전탐색/모음사전/PGS_모음사전_이지영.java
  완전탐색/전력망을 둘로 나누기/PGS_전력망을둘로나누기_이지영.java
  완전탐색/피로도/PGS_피로도_이지영.java
Labels: ✨ Submit

#11 [4주차] 과제 제출합니다.
  완전탐색/모음사전/PGS_모음사전_홍예진.java
  완전탐색/전력망을 둘로 나누기/PGS_전력망을둘로나누기_홍예진.java
  완전탐색/피로도/PGS_피로도_홍예진.java
Labels: ✨ Submit

#13 [4주차] 과제 제출합니다.
  BFS-DFS/게임 맵 최단거리/PGS_게임맵최단거리_주한.cpp
  BFS-DFS/네트워크/PGS_네트워크_주한.cpp
  BFS-DFS/단어 변환/PGS_단어변환_김주한.cpp
  BFS-DFS/여행경로/PGS_여행경로_김주한.cpp
  BFS-DFS/타겟 넘버/PGS_타켓넘버_주한.cpp
  완전탐색/모음사전/PGS_모음사전_김주한.cpp
  완전탐색/모의고사/PGS_모의고사_김주한.cpp
  완전탐색/소수 찾기/PGS_소수찾기_김주한.cpp
  완전탐색/전력망을 둘로 나누기/PGS_전력망을둘로나누기_김주한.cpp
  완전탐색/최소직사각형/PGS_최소직사각형_김주한.cpp
  완전탐색/카펫/PGS_카펫_김주한.cpp
  완전탐색/피로도/PGS_피로도_김주한.cpp
Labels: ✨ Submit, 🔨 Refactor

#15 [4주차] 과제 수정본 제출합니다
  완전탐색/전력망을 둘로 나누기/PGS_전력망을둘로나누기_이지영.java
  완전탐색/피로도/PGS_피로도_이지영.java
Labels: 🔨 Refactor

#19 [5주차] 과제 제출합니다.
  DP/N으로 표현/PGS_N으로표현_공진호.java
  DP/등굣길/PGS_등굣길_공진호.java
  DP/정수 삼각형/PGS_정수삼각형_공진호.java
Labels: ✨ Submit

#18 [5주차] 과제 제출합니다.
  DP/N으로 표현/PGS_N으로표현_이지영.java
  DP/등굣길/PGS_등굣길_이지영.java
  DP/정수 삼각형/PGS_정수삼각형_이지영.java
Labels: ✨ Submit

#22 [6주차] 과제 제출합니다.
  DP/도둑질/PGS_도둑질_공진호.java
  DP/사칙연산/PGS_사칙연산_공진호.java
Labels: ✨ Submit

#21 [6주차] 과제 제출합니다.
  DP/도둑질/PGS_도둑질_이지영.cpp
  DP/도둑질/PGS_도둑질_이지영.java
  DP/사칙연산/PGS_사칙연산_이지영.java
Labels: ✨ Submit
